application: challenger-dev1
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /vendor
  static_dir: vendor
- url: /static
  static_dir: static

- url: /applications.*
  script: applications.app
- url: /users.*
  script: users.app
- url: /matches/.*
  script: matches.app

libraries:
- name: jinja2
  version: latest