{print} = require 'util'
{exec} = require 'child_process'

build = (callback) ->
	coffee = spawn 'coffee', ['-c', '-o', '../server/static', 'source']
	coffee.stderr.on 'data', (data) ->
		process.stderr.write data.toString()
	coffee.stdout.on 'data', (data) ->
		print data.toString()
	coffee.on 'exit', (code) ->
		callback?() if code is 0

ls = (callback) ->
	exec 'ls', callback


task 'build', 'Build ../server/static from source/', ->
	build()

task 'test', 'run tests', -> 
	ls()